-- =============================================================================
-- Admin backend accounts (username/password)
-- Execute in Supabase Dashboard -> SQL Editor
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.admin_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.touch_admin_accounts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_admin_accounts_updated_at ON public.admin_accounts;
CREATE TRIGGER trg_admin_accounts_updated_at
BEFORE UPDATE ON public.admin_accounts
FOR EACH ROW
EXECUTE FUNCTION public.touch_admin_accounts_updated_at();

CREATE INDEX IF NOT EXISTS idx_admin_accounts_username ON public.admin_accounts (username);

-- Initial admin accounts (all same permission).
-- IMPORTANT: store these initial passwords safely and rotate after first login.
-- admin-1: U9iSb6eH
-- admin-2: sEQF54@y
-- admin-3: XT%eJCi6
-- admin-4: GJPSwnNx
-- admin-5: JcaRHgDD
INSERT INTO public.admin_accounts (username, password_hash, is_active)
VALUES
  ('admin-1', 'scrypt$75473bd3538ad9c706860069f420ebf6$b3c6304cbb935b4b23036c12a0cfa5fb9067182b9c12ac2d14de039854d4a87d33e69506b7ba45bb4debf0aef95d6c3c3a2271854bf51d5edf54ced413f91551', true),
  ('admin-2', 'scrypt$8c00dd57e186c68f7828486b16211349$58569c44ace8397145555cab57376b6eb4f251421d675713855de0bf1966edbaf69560fd47397473fa77bfccd165385588dd8fe27d9d9c8825a205e16f1ae824', true),
  ('admin-3', 'scrypt$3bf1ad4b8842de2fd3aa915e53216d0d$f2dc4eb66ecc07b63b763cecb2d1c5fcbd1525d68ee9f59b28b1a8cf3f8b47a42a9ba85e07ecbf8eeec7ca57ab79056063454a6a37012090cf41b29c58b815c5', true),
  ('admin-4', 'scrypt$78ee1754016f97341988c90f84cb9ade$7f9daf93db7a51204fa3c58137ba11dc5d5cce1ae10c92141c6df662e4e3e86df58449ae96c3a91b0ec7afc09619f8a8836783d48e8f137573c91f0203bde890', true),
  ('admin-5', 'scrypt$602fd7e0b883915e4321fbfc43daa33a$1124ef5f7a37e88d40118e06092585f91623d962791f5a8ebe2a781552a50c0637351140a5f0d94de78e1089bb027cfa28dff7a795c58f84ea7d3b317e0a0536', true)
ON CONFLICT (username) DO UPDATE
SET
  password_hash = EXCLUDED.password_hash,
  is_active = EXCLUDED.is_active;
